default_platform(:ios)
platform :ios do
  desc "Description of what the lane does"
  lane :generate_ipa_develop do
  cocoapods(
      clean_install: true,
      podfile: "./Podfile"
    )
    build_ios_app(
      configuration: "Debug",
      scheme: "Numero",
      clean: true,
      export_method: 'development',
      output_directory: "~/Desktop", # Destination directory. Defaults to current directory.
      output_name: "Numero.ipa",
    )
  end
    lane :release do
    api_key = app_store_connect_api_key(
      key_id: "ZSQSTQH5HP",
      issuer_id: "69a6de94-1373-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./AuthKey_D383SF739.p8",
      duration: 1200, # optional
      in_house: false, # optional but may be required if using match/sigh
    )
    pilot(api_key: api_key)
  end
end